version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13.10
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: .env
  
  backend:
    image: maksimmoryakov/kittygram_backend
    env_file: .env
    volumes:
      - static:/backend_static
      - media:/media
    depends_on:
      - db

  frontend:
    image: maksimmoryakov/kittygram_frontend
    command: cp -r /app/build/. /frontend_static/
    volumes:
      - static:/frontend_static
 
  gateway:
    image: maksimmoryakov/kittygram_gateway
    env_file: .env
    ports:
      - 9000:80
    volumes:
      - static:/static
      - media:/media
    depends_on:
      - backend
      - frontend
